version: "3.9"

services:
  nginx-media:
    image: nginx:1.26-alpine
    container_name: nginx-media
    ports:
      - "8080:80"
    volumes:
      - ../../../media:/media:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
